In [75]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import string
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


In [76]:
heart_data = pd.read_csv('heart_disease_data.csv')
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, stratify=Y, random_state=2)

In [77]:
LR = LogisticRegression()
LR.fit(X_train, Y_train)
pred_lr = LR.predict(X_test)
print("Accuracy score for Logistics Regression")
print(LR.score(X_test,Y_test))


Accuracy score for Logistics Regression
0.819672131147541


C:\Users\bunde\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [78]:
L = LinearRegression()
L.fit(X_train, Y_train)
pred_L = L.predict(X_test)
print("Accuracy score for Logistics Regression")
print(LR.score(X_test,Y_test))

Accuracy score for Logistics Regression
0.819672131147541


In [79]:
sv = SVC()
sv.fit(X_train, Y_train)
pred_lr = sv.predict(X_test)
print("Accuracy score for Logistics Regression")
print(sv.score(X_test,Y_test))

Accuracy score for Logistics Regression
0.6229508196721312


In [80]:
DT=DecisionTreeClassifier()
DT.fit(X_train, Y_train)
pred_dt = DT.predict(X_test)
print("Accuracy score for Decision Tree")
print(DT.score(X_test,Y_test))

Accuracy score for Decision Tree
0.7868852459016393


In [81]:
RF=RandomForestClassifier()
RF.fit(X_train, Y_train)
pred_rf = RF.predict(X_test)
print("Accuracy score for Random Forest")
print(RF.score(X_test,Y_test))

Accuracy score for Random Forest
0.7704918032786885


In [82]:
print(confusion_matrix(Y_test, pred_lr))
print(classification_report(Y_test, pred_lr))

[[13 15]
 [ 8 25]]
              precision    recall  f1-score   support

           0       0.62      0.46      0.53        28
           1       0.62      0.76      0.68        33

    accuracy                           0.62        61
   macro avg       0.62      0.61      0.61        61
weighted avg       0.62      0.62      0.61        61



In [83]:
print(confusion_matrix(Y_test, pred_dt))
print(classification_report(Y_test, pred_dt))

[[21  7]
 [ 6 27]]
              precision    recall  f1-score   support

           0       0.78      0.75      0.76        28
           1       0.79      0.82      0.81        33

    accuracy                           0.79        61
   macro avg       0.79      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61



In [84]:
print(confusion_matrix(Y_test, pred_rf))
print(classification_report(Y_test, pred_rf))

[[21  7]
 [ 7 26]]
              precision    recall  f1-score   support

           0       0.75      0.75      0.75        28
           1       0.79      0.79      0.79        33

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

